// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication9.Data;

#nullable disable

namespace WebApplication9.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication9.Models.Employee", b =>
                {
                    b.Property<int>("Emp_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Emp_No"), 1L, 1);

                    b.Property<double>("Contact_No")
                        .HasColumnType("float");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOJ")
                        .HasColumnType("datetime2");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Emp_No");

                    b.ToTable("Employes");
                });

            modelBuilder.Entity("WebApplication9.Models.Salary", b =>
                {
                    b.Property<int>("Sal_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sal_Id"), 1L, 1);

                    b.Property<decimal>("Basic")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Emp_No")
                        .HasColumnType("int");

                    b.Property<decimal>("FA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HRA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ME")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SY")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("month_year")
                        .HasColumnType("datetime2");

                    b.HasKey("Sal_Id");

                    b.HasIndex("Emp_No");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("WebApplication9.Models.Salary", b =>
                {
                    b.HasOne("WebApplication9.Models.Employee", "id")
                        .WithMany()
                        .HasForeignKey("Emp_No")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("id");
                });
#pragma warning restore 612, 618
        }
    }
}
